spring:
  application:
    name: expense-manager-api
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username:
    password:
    platform: org.hibernate.dialect.H2Dialect
  jpa:
    open-in-view: true
  devtools:
    add-properties: true
